# Generated by Django 3.2.2 on 2022-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0002_tbl_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
