# Generated by Django 3.2.2 on 2022-01-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0004_auto_20220107_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_supplier',
            name='comapany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syspos.tbl_user'),
        ),
    ]
