# Generated by Django 3.2.2 on 2022-01-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0005_alter_tbl_supplier_comapany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_supplier',
            name='comapany',
            field=models.IntegerField(null=True),
        ),
    ]
