# Generated by Django 3.2.2 on 2022-01-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0006_alter_tbl_supplier_comapany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_supplier',
            old_name='comapany',
            new_name='company',
        ),
    ]
