# Generated by Django 3.2.2 on 2022-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspos', '0008_auto_20220110_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_warehouse',
            name='company',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_warehouse',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
